export const regions = [
  {
    name: 'Coimbatore',
    area: 'Tamil Nadu, India',
    size: '1,247 km²',
    latitude: 11.0168,
    longitude: 76.9558,
    bbox: [76.72, 10.82, 77.2, 11.24],
    health: 78,
    forest: '31.8%',
    water: '64/100',
    built: '+2.8%',
    forestChange: '+1.6%',
    waterChange: '−2.1%',
    builtChange: 'watch',
    missionCount: '06',
    canopyScore: 82,
    waterScore: 64,
    urbanScore: 87,
    insight: 'The region is moving in a healthy direction overall. Canopy recovery is a bright spot, while water change deserves a closer look.',
  },
  {
    name: 'Chennai',
    area: 'Tamil Nadu, India',
    size: '1,118 km²',
    latitude: 13.0827,
    longitude: 80.2707,
    bbox: [80.04, 12.84, 80.48, 13.3],
    health: 71,
    forest: '18.6%',
    water: '59/100',
    built: '+5.1%',
    forestChange: '−0.8%',
    waterChange: '−4.7%',
    builtChange: 'rising',
    missionCount: '09',
    canopyScore: 68,
    waterScore: 59,
    urbanScore: 76,
    insight: 'Coastal growth is putting pressure on water and green cover. Targeted urban restoration could protect several connected neighborhoods.',
  },
  {
    name: 'Bengaluru',
    area: 'Karnataka, India',
    size: '1,428 km²',
    latitude: 12.9716,
    longitude: 77.5946,
    bbox: [77.35, 12.75, 77.82, 13.18],
    health: 66,
    forest: '24.3%',
    water: '52/100',
    built: '+7.4%',
    forestChange: '−1.9%',
    waterChange: '−6.2%',
    builtChange: 'rising',
    missionCount: '12',
    canopyScore: 61,
    waterScore: 52,
    urbanScore: 69,
    insight: 'Rapid built-up expansion is visible at the edges. Protecting connected green corridors will matter more as the city grows.',
  },
  {
    name: 'Ooty',
    area: 'Nilgiris, India',
    size: '224 km²',
    latitude: 11.4102,
    longitude: 76.695,
    bbox: [76.52, 11.22, 76.9, 11.58],
    health: 86,
    forest: '47.2%',
    water: '91/100',
    built: '+0.9%',
    forestChange: '+2.2%',
    waterChange: '+0.6%',
    builtChange: 'stable',
    missionCount: '04',
    canopyScore: 93,
    waterScore: 91,
    urbanScore: 74,
    insight: 'Highland ecosystems are comparatively strong. Slow, well-placed restoration can preserve the balance as visitor pressure grows.',
  },
];

export const missionDetails = {
  'Neighbourhood canopy': {
    category: 'forest',
    categoryLabel: 'FOREST',
    location: 'Vellaiyar forest edge',
    date: 'This Saturday · 07:30 AM',
    distance: '2.4 km',
    participants: 18,
    credits: 40,
    organizer: 'Coimbatore Green Collective',
    description: 'Plant and care for native saplings along a neighbourhood edge, then record survival observations for the next 90 days.',
    impact: '14 native saplings · 0.8 ha restored',
    evidence: 'Before-and-after photos, planting date, and a simple survival count',
    icon: 'tree',
  },
  'Lake watch & clean-up': {
    category: 'water',
    categoryLabel: 'WATER',
    location: 'Ukkamaram Lake',
    date: '28 Sep · 06:45 AM',
    distance: '4.1 km',
    participants: 12,
    credits: 60,
    organizer: 'Ukkamaram Neighbourhood Network',
    description: 'Help clear litter and record observations around Ukkamaram Lake so the water-body trend can be compared over time.',
    impact: '18 kg litter collected · 6 water observations',
    evidence: 'Collection log, location pin, and three observation photos',
    icon: 'water',
  },
  'Green school day': {
    category: 'community',
    categoryLabel: 'COMMUNITY',
    location: 'Green Valley campus',
    date: '05 Oct · 09:00 AM',
    distance: '6.8 km',
    participants: 31,
    credits: 25,
    organizer: 'Green Valley Schools',
    description: 'Run a waste-free, nature-positive day with your campus through a waste audit, tree care, and a student-led awareness session.',
    impact: '1 campus · 120 students engaged',
    evidence: 'Activity summary, consent-safe group photo, and waste audit',
    icon: 'award',
  },
  'Wetland guardians': {
    category: 'forest',
    categoryLabel: 'FOREST',
    location: 'Kuniyur wetland edge',
    date: '12 Oct · 07:00 AM',
    distance: '8.2 km',
    participants: 9,
    credits: 50,
    organizer: 'Nilgiri Habitat Collective',
    description: 'Support native habitat restoration and monthly water checks in a wetland edge that is not yet fully visible in public maps.',
    impact: '0.4 ha habitat monitored · 3 water checks',
    evidence: 'Field notes, location pin, and a habitat photo set',
    icon: 'park',
  },
  'Shade walk': {
    category: 'community',
    categoryLabel: 'COMMUNITY',
    location: 'R.S. Puram walking loop',
    date: '19 Oct · 06:30 AM',
    distance: '3.7 km',
    participants: 14,
    credits: 30,
    organizer: 'Urban Commons Collective',
    description: 'Map unsafe heat exposure along a busy walking route and care for young shade trees already established nearby.',
    impact: '1.8 km route mapped · 12 shade trees cared for',
    evidence: 'Route map, temperature observations, and tree-care photos',
    icon: 'tree',
  },
  'Waste-less market': {
    category: 'community',
    categoryLabel: 'COMMUNITY',
    location: 'Saibaba Colony market',
    date: '26 Oct · 08:00 AM',
    distance: '5.6 km',
    participants: 21,
    credits: 35,
    organizer: 'Saibaba Residents Association',
    description: 'Help a neighbourhood market document waste segregation and co-design a practical reduction plan with vendors.',
    impact: '1 market audited · 3 waste streams mapped',
    evidence: 'Waste audit sheet, vendor summary, and consent-safe photos',
    icon: 'waste',
  },
};

export const missionStatuses = [
  { key: 'open', label: 'Open', shortLabel: 'Open' },
  { key: 'accepted', label: 'Accepted', shortLabel: 'Accepted' },
  { key: 'in-progress', label: 'In progress', shortLabel: 'In progress' },
  { key: 'evidence-submitted', label: 'Evidence submitted', shortLabel: 'Evidence' },
  { key: 'verified', label: 'Verified', shortLabel: 'Verified' },
  { key: 'completed', label: 'Completed', shortLabel: 'Completed' },
];

export const initialBuilder = {
  greenery: 38,
  water: 42,
  air: 71,
  density: 54,
};
